# config map
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DATABASE_URL: "jdbc:postgresql://postgres-svc/postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  POSTGRES_PASSWORD: "<PUT YOUR ROOT PASSWORD HERE>"    # postgres root password
  DATABASE_USERNAME: "<PUT YOUR DB USER HERE>"          # app db user
  DATABASE_PASSWORD: "<PUT YOUR DB PASSWORD HERE>"      # app db password
